### ISSUE TITLE
some checks were not successful 

### ISSUE THREAD

**Issue by unique379** [Edinburgh-Genome-Foundry/pdf_reports#10]
Hi
Thank you for making nice lib for the easy pdf report.
Can you please update your branch again as it says "some checks were not successful " which leads corrupted cloning, specially example pug templates.

**Comment by veghp** [comment]
Hi, thanks for trying out this package. Can you please clarify your error? [Build tests](https://travis-ci.org/github/Edinburgh-Genome-Foundry/pdf_reports) were fine. What code are you trying to run, and what OS are you using?
