### ISSUE TITLE
Pdf reports not working in ubuntu

### ISSUE THREAD

**Issue by rose-ramasamy** [Edinburgh-Genome-Foundry/pdf_reports#17]
Hi team,

I am trying to use the weasyprint pdf reports and the library is not loading properly in ubuntu.

When I run my python program I am getting the following error.

OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': libcairo.so.2: cannot open shared object file: No such file or directory

![pdf_report_error](https://user-images.githubusercontent.com/79498854/115522953-3313ae80-a2aa-11eb-86b5-daf1b31bcb13.PNG)

**Comment by veghp** [comment]
hi, PDF reports depends on weasyprint. As the error says, a dependency of weasyprint, Cairo, hasn't been installed. Have you installed it according to the instructions at: https://weasyprint.readthedocs.io/en/stable/install.html#linux
