### ISSUE TITLE
SASS/SCSS support

### ISSUE THREAD

**Issue by mwcm** [Edinburgh-Genome-Foundry/pdf_reports#2]
SASS/SCSS and PUG are often used together, It would be nice to be able to input `.scss` or `.sass` files instead of pure CSS and have either pdf_reports or Weasyprint automatically preprocess it. 

I'm currently using [libsass](https://sass.github.io/libsass-python/index.html) to do this, with a helper function similar to this:
```python
import sass

def scss_to_css(scss_path, log):
    ''' convert and copy a .scss file to a .css file in the same directory '''
    if '.sass' in scss_path:
        css_path = scss_path.replace('.sass', '.css')
    elif '.scss' in scss_path:
        css_path = scss_path.replace('.scss', '.css')
    elif '.css' in scss_path:
        return scss_path
    try:
        stylesheet = sass.compile(filename=scss_path)
        with open(css_path, 'w') as css_file:
            css_file.write(stylesheet)
            css_file.close()
    except Exception as e:
        log(e)
        return

    return css_path
```
and this usage:
```python
from pdf_reports import pug_to_html, write_report
from util import scss_to_css

pug_path = '/some/path/file.pug'
scss_path = '/some/path/file.scss'
pdf_path = '/some/path/file.pdf'
css_path = scss_to_css(scss_path, log)
html = pug_to_html(pug_path, title='some_title')
write_report(html, pdf_path, extra_stylesheets=(css_path,))
```
This is okay for now, but I'd like to be able to pass `.scss` or `.sass` files straight to the `write_report` function.

Specifically speaking of the `extra_stylesheets` argument to the `write_report` function in `pdf_reports.py`.

might be as easy as something like this:
```python 
import scss_to_css
def write_report(html, target=None, base_url=None, use_default_styling=True,
                 extra_stylesheets=()):
    for stylesheet in extra_stylesheets:
        stylesheet = scss_to_css(stylesheet)
```

One last thing: it would also be nice to change the extra_stylesheets Tuple into an array:
Then we would avoid the `write_report(html, pdf_path, extra_stylesheets=(css_path,))` notation in the case that the user  only one inputs one extra style sheet. (ex: If `css_path` is passed without the surrounding `(,)` it is interpreted as a `str` rather than a Tuple, then throws an error)

I can add this functionality, just wanted to make a feature request before I started working on a PR :)

If this PR should be against Weasyprint instead just let me know and I'll move it over. Assumed it should be here since you're handling the PUG processing here too.

**Comment by Zulko** [comment]
Ok for adding scss support but there are several things in your implementation which I'd change, e.g. to avoid failing silently or support for weasyprint CSS objects, so let me do the PR. Could be in a week or two.

**Comment by mwcm** [comment]
sure! of course, just wanted to share a minimal example, thanks for looking into it!

**Comment by Zulko** [comment]
In the end I went for a mid-solution: there is now a ``preload_stylesheet`` method which will load and parse any CSS or SCSS (if you have the Python libsass library installed). See the readme for more. I hope that's helpfull.

**Comment by mwcm** [comment]
that's perfect, thank you :D
