### ISSUE TITLE
Create API Documentation

### ISSUE THREAD

**Issue by JoshuaC3** [Edinburgh-Genome-Foundry/pdf_reports#6]
There is no documentation on the Package's API. This would be really useful.

**Comment by Zulko** [comment]
What about [this page](https://edinburgh-genome-foundry.github.io/pdf_reports/ref.html). I can probably expand it if you want.

**Comment by JoshuaC3** [comment]
Alright! This is what I was looking for. It was the title REFERENCE alone made me assume it was paper references. Maybe API Reference would be a slightly better title but realise this was me being a numpty!!
